_target_: src.simplenet_learner.models.simplenet2d_module.Simplenet2DModule

anomaly_threshold: 0.8
size_of_predict_mask:
  - ${datamodule.transform_cfg.crop_h}
  - ${datamodule.transform_cfg.crop_w}

simplenet2d_cfg:
  backborn_arch: resnet18
  backborn_pretrained: True
  backborn_trainable: False
  projection_channel: 384
  projection_layer_num: 1
  discriminator_layer_num: 3
  discriminator_reduce_rate: 1.5
  use_backborn_layers: "2_3"
  patch_size: 2

projection_optimizer_cfg:
  name: AdamW
  lr: 0.0001
  betas:
    - 0.9
    - 0.999
  eps: 1e-8
  weight_decay: 0

projection_lr_scheduler_cfg: null

discriminator_optimizer_cfg:
  name: Adam
  lr: 0.0002
  betas:
    - 0.9
    - 0.999
  eps: 1e-8
  weight_decay: 0

discriminator_lr_scheduler_cfg:
  name: CosineAnnealingLR
  T_max: ${trainer.max_epochs}
  eta_min: 8e-5

noise_generator:
  _target_: src.simplenet_learner.utils.noise_generator.SpatiallyIndependentNoiseGenerator2D
  noise_std: 0.015
  noise_type: normal
  noise_scaling: 1.1
  num_clsses: 1
