model_checkpoint:
  _target_: lightning.callbacks.ModelCheckpoint
  monitor: "val/acc" # name of the logged metric which determines when model is improving
  mode: "max" # "max" means higher metric value is better, can be also "min"
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  every_n_train_steps: 0
  every_n_epochs: 10
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

early_stopping:
  _target_: lightning.callbacks.EarlyStopping
  monitor: "val/acc" # name of the logged metric which determines when model is improving
  mode: "max" # "max" means higher metric value is better, can be also "min"
  patience: 100 # how many validation epochs of not improving until training stops
  min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement

model_summary:
  _target_: lightning.callbacks.RichModelSummary
  max_depth: -1

rich_progress_bar:
  _target_: lightning.callbacks.RichProgressBar

lr_monitor:
  _target_: lightning.callbacks.lr_monitor.LearningRateMonitor
  logging_interval: "epoch"
