_target_: lightning.Trainer

accelerator: "gpu" # CPU or GPU
devices: -1 # 使用するGPUの枚数

min_epochs: 1
max_epochs: 15 # 学習エポック数

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

